package com.aluracursos.forohub.domain.topic;

public enum Category {
    INTRO_TO_COMPUTER_SCIENCE,
    JAVA_PROGRAMMING_BASICS,
    FRONTEND_DEVELOPMENT,
    RELATIONAL_DATABASES,
    CYBERSECURITY_FUNDAMENTALS,
    ALGORITHMS_AND_DATA_STRUCTURES,
    SOFTWARE_DESIGN_PATTERNS,
    CLOUD_SERVICES_OVERVIEW,
    IOS_APP_DEVELOPMENT,
    AI_AND_DEEP_LEARNING
}